### ISSUE TITLE
NoMethodError - undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by jriram** [r509/r509-ca-http#33]
Hi,

when using the `test/certificate/issue` form to create a new certificate, I got this error message:

**NoMethodError - undefined method `[]' for nil:NilClass**

The stack trace is:

```
I, [2014-03-18T17:01:15.122286 #10298]  INFO -- : Issue Certificate
I, [2014-03-18T17:01:15.122472 #10298]  INFO -- : ca=r509_ca&profile=&validityPeriod=&subject%5BC%5D=&subject%5BST%5D=&subject%5BL%5D=&subject%5BO%5D=&subject%5BOU%5D=&subject%5BCN%5D=&subject%5BemailAddress%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&csr=
I, [2014-03-18T17:01:15.122615 #10298]  INFO -- : {"ca"=>"r509_ca", "profile"=>"", "validityPeriod"=>"", "subject"=>{"C"=>"", "ST"=>"", "L"=>"", "O"=>"", "OU"=>"", "CN"=>"", "emailAddress"=>""}, "extensions"=>{"subjectAlternativeName"=>["", "", "", "", ""]}, "csr"=>""}
NoMethodError - undefined method `[]' for nil:NilClass:
    /usr/lib64/ruby/gems/2.0.0/gems/r509-ca-http-0.3.1/lib/r509/certificateauthority/http/server.rb:47:in `ca'
    /usr/lib64/ruby/gems/2.0.0/gems/r509-ca-http-0.3.1/lib/r509/certificateauthority/http/server.rb:114:in `block in <class:Server>'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1593:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1593:in `block in compile!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `[]'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (3 levels) in route!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:976:in `route_eval'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (2 levels) in route!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:997:in `block in process_route'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `catch'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `process_route'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:955:in `block in route!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `each'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `route!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1067:in `block in dispatch!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1064:in `dispatch!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `block in call!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `call!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:877:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:180:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:2004:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `block in call'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1778:in `synchronize'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/r509-middleware-certwriter-0.2.1/lib/r509/middleware/certwriter.rb:20:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/r509-middleware-validity-0.2.1/lib/r509/middleware/validity.rb:20:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:217:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
    /usr/lib64/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
    /usr/lib64/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
    /usr/lib64/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

Any idea what could be wrong?

**Comment by reaperhulk** [comment]
Looks like it can't find the certificate authority you specified. Does your config.yaml have a `r509_ca` CA? It also looks like you didn't specify a profile name, which is also required.

**Comment by jriram** [comment]
Yes, the `r509_ca` CA exists in the `config.yaml`, below this file's content:

``` yaml
---
certificate_authorities:
  r509_ca:
    ca_cert:
      cert: root.cer
      key: root.key
    ocsp_start_skew_seconds: 3600
    ocsp_validity_hours: 24
    crl_list_file: r509_ca_list.txt
    crl_number_file: r509_ca_crlnumber.txt
    crl_validity_hours: 24
    crl_md: SHA256
    profiles:
      # This profile is for generating client certificates
      client:
        basic_constraints:
          :ca: false
        key_usage:
          :value:
          - digitalSignature
          - keyEncipherment
        extended_key_usage:
          :value:
          - clientAuth
        authority_info_access:
          :critical: false
          :ocsp_location:
          - :type: URI
            :value: http://ocsp.myca.com:9291
        allowed_mds:
        - SHA256
        default_md: SHA256
        subject_item_policy:
          CN:
            :policy: required
          O:
            :policy: required
          OU:
            :policy: required
          C:
            :policy: required
          ST:
            :policy: required
          L:
            :policy: required

# Where to write the generated certs
certwriter:
  path: /home/jrios/r509-ca/generated-certs
```

I can even see it's read when starting the rack server (OCSP and CRL validity):

```
rackup -p 9292
I, [2014-03-19T08:40:40.607406 #11170]  INFO -- : Using r509 middleware validity
I, [2014-03-19T08:40:40.610012 #11170]  INFO -- : Using r509 middleware certwriter
I, [2014-03-19T08:40:40.791170 #11170]  INFO -- : Config: 
I, [2014-03-19T08:40:40.791416 #11170]  INFO -- : CA Cert:/C=MX/ST=Mexico City/L=Miguel Hidalgo/O=Schibsted Classified Media/OU=Segundamano.mx/CN=Segundamano.mx Root CA
I, [2014-03-19T08:40:40.791556 #11170]  INFO -- : OCSP Cert (may be the same as above):/C=MX/ST=Mexico City/L=Miguel Hidalgo/O=Schibsted Classified Media/OU=Segundamano.mx/CN=Segundamano.mx Root CA
I, [2014-03-19T08:40:40.791636 #11170]  INFO -- : OCSP Validity Hours: 24
I, [2014-03-19T08:40:40.791702 #11170]  INFO -- : CRL Validity Hours: 24
I, [2014-03-19T08:40:40.791760 #11170]  INFO -- :
```

Did another test filling in all the fields, and still getting the error:

```
I, [2014-03-19T08:44:06.867304 #11170]  INFO -- : Issue Certificate
I, [2014-03-19T08:44:06.867633 #11170]  INFO -- : ca=r509_ca&profile=client&validityPeriod=31536000&subject%5BC%5D=MX&subject%5BST%5D=Mexico+City&subject%5BL%5D=Coyoacan&subject%5BO%5D=Intermive&subject%5BOU%5D=Moderation&subject%5BCN%5D=Jose+Rios&subject%5BemailAddress%5D=jose.rios%40schibsted.com.mx&extensions%5BsubjectAlternativeName%5D%5B%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&extensions%5BsubjectAlternativeName%5D%5B%5D=&csr=-----BEGIN+CERTIFICATE+REQUEST-----%0D%0AMIICuDCCAaACAQAwczELMAkGA1UEBhMCTVgxFDASBgNVBAgMC01leGljbyBDaXR5%0D%0AMREwDwYDVQQHDAhDb3lvYWNhbjESMBAGA1UECgwJSW50ZXJtaXZlMRMwEQYDVQQL%0D%0ADApNb2RlcmF0aW9uMRIwEAYDVQQDDAlKb3NlIFJpb3MwggEiMA0GCSqGSIb3DQEB%0D%0AAQUAA4IBDwAwggEKAoIBAQDSbgmb%2Bv7gelBrqzjCDZxbU6My6zrgPx%2F8%2FZmbOkUt%0D%0ARHVQF3lEsq86PKvTXt2O%2BZDG3jM3blgs1udReFBBPSN5zvFavHcjrMxIj4WAYAS8%0D%0Apk4%2F1HYoZcxthvzuwZn3IVeYojPLM4yYbu0Gkv%2BUMg3OcngkzfLOUUbdxNTqe2y4%0D%0AmmNkRqsUJTiygT9zyupJYq%2FmX4tWe6AkPy6aBTp0%2B3Ntl5OHaD%2B9ps8gPHUJQDIE%0D%0A%2BpkH0sA7wqGEbRvse7uV9OwCrXEU%2F7zH4mq9WWKajC7Eiwanim7A8IWqL3DiIurS%0D%0APBHQsfWukhaN2HmgHdYYb559iqyEyGju0hFlPq6oq3AvAgMBAAGgADANBgkqhkiG%0D%0A9w0BAQUFAAOCAQEAT6ppkPYcQwqF1%2FOYKPcu3GQBEXPG1jM1PxBWj%2F1VJICGSWoC%0D%0AFMVazTR%2BlhUUnlLCwUxzIlM4%2BZeLsEadIqHH%2FfDDEnNasUQ8fXoG864EgRLkQUUW%0D%0AK1Mk6w8qj%2FYqVi2Us5bVjVp8TYDfgKv7ZxlFN6QzLfad%2BLsg3%2B0P4myCc4rG9EMG%0D%0AfHdO7etz9mhH6q%2B9xjYRvCx0ewUxEZD91dc1nncfDyUmfIoa97TbJJ%2FYmVM2uqgr%0D%0AyDNJUjUFJqQddCeD1HyPS8JDptzq0azUadqQ0HSGIC339QDYVw%2FhP3F0MaRpgsdy%0D%0AF4Nx4CwOoDsSKEoEILpiAYjUAFiWzMs8bRuAfQ%3D%3D%0D%0A-----END+CERTIFICATE+REQUEST-----
I, [2014-03-19T08:44:06.867862 #11170]  INFO -- : {"ca"=>"r509_ca", "profile"=>"client", "validityPeriod"=>"31536000", "subject"=>{"C"=>"MX", "ST"=>"Mexico City", "L"=>"Coyoacan", "O"=>"Intermive", "OU"=>"Moderation", "CN"=>"Jose Rios", "emailAddress"=>"jose.rios@schibsted.com.mx"}, "extensions"=>{"subjectAlternativeName"=>["", "", "", "", ""]}, "csr"=>"-----BEGIN CERTIFICATE REQUEST-----\r\nMIICuDCCAaACAQAwczELMAkGA1UEBhMCTVgxFDASBgNVBAgMC01leGljbyBDaXR5\r\nMREwDwYDVQQHDAhDb3lvYWNhbjESMBAGA1UECgwJSW50ZXJtaXZlMRMwEQYDVQQL\r\nDApNb2RlcmF0aW9uMRIwEAYDVQQDDAlKb3NlIFJpb3MwggEiMA0GCSqGSIb3DQEB\r\nAQUAA4IBDwAwggEKAoIBAQDSbgmb+v7gelBrqzjCDZxbU6My6zrgPx/8/ZmbOkUt\r\nRHVQF3lEsq86PKvTXt2O+ZDG3jM3blgs1udReFBBPSN5zvFavHcjrMxIj4WAYAS8\r\npk4/1HYoZcxthvzuwZn3IVeYojPLM4yYbu0Gkv+UMg3OcngkzfLOUUbdxNTqe2y4\r\nmmNkRqsUJTiygT9zyupJYq/mX4tWe6AkPy6aBTp0+3Ntl5OHaD+9ps8gPHUJQDIE\r\n+pkH0sA7wqGEbRvse7uV9OwCrXEU/7zH4mq9WWKajC7Eiwanim7A8IWqL3DiIurS\r\nPBHQsfWukhaN2HmgHdYYb559iqyEyGju0hFlPq6oq3AvAgMBAAGgADANBgkqhkiG\r\n9w0BAQUFAAOCAQEAT6ppkPYcQwqF1/OYKPcu3GQBEXPG1jM1PxBWj/1VJICGSWoC\r\nFMVazTR+lhUUnlLCwUxzIlM4+ZeLsEadIqHH/fDDEnNasUQ8fXoG864EgRLkQUUW\r\nK1Mk6w8qj/YqVi2Us5bVjVp8TYDfgKv7ZxlFN6QzLfad+Lsg3+0P4myCc4rG9EMG\r\nfHdO7etz9mhH6q+9xjYRvCx0ewUxEZD91dc1nncfDyUmfIoa97TbJJ/YmVM2uqgr\r\nyDNJUjUFJqQddCeD1HyPS8JDptzq0azUadqQ0HSGIC339QDYVw/hP3F0MaRpgsdy\r\nF4Nx4CwOoDsSKEoEILpiAYjUAFiWzMs8bRuAfQ==\r\n-----END CERTIFICATE REQUEST-----"}
NoMethodError - undefined method `[]' for nil:NilClass:
    /usr/lib64/ruby/gems/2.0.0/gems/r509-ca-http-0.3.1/lib/r509/certificateauthority/http/server.rb:47:in `ca'
    /usr/lib64/ruby/gems/2.0.0/gems/r509-ca-http-0.3.1/lib/r509/certificateauthority/http/server.rb:114:in `block in <class:Server>'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1593:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1593:in `block in compile!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `[]'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (3 levels) in route!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:976:in `route_eval'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:957:in `block (2 levels) in route!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:997:in `block in process_route'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `catch'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:995:in `process_route'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:955:in `block in route!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `each'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:954:in `route!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1067:in `block in dispatch!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1064:in `dispatch!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `block in call!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `block in invoke'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `catch'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1049:in `invoke'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:889:in `call!'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:877:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:180:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:2004:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `block in call'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1778:in `synchronize'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:1469:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/r509-middleware-certwriter-0.2.1/lib/r509/middleware/certwriter.rb:20:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/r509-middleware-validity-0.2.1/lib/r509/middleware/validity.rb:20:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/sinatra-1.4.4/lib/sinatra/base.rb:217:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
    /usr/lib64/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
    /usr/lib64/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
    /usr/lib64/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
    /usr/lib64/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by jriram** [comment]
I have checkout the `5effdb6` commit, build the gem using the code as this commit, and installed the `r509-ca-http-0.3.0.gem` and then it works. So I think it must be a later change that breaks it, I am reviewing the code after that commit.

**Comment by reaperhulk** [comment]
Thanks for investigating this @jriram!

**Comment by jriram** [comment]
After bisecting, the commit that breaks it is: `f4fda48`. Still reviewing the changes introduced by this commit.

**Comment by reedloden** [comment]
hmm, author of f4fda48de377f227f6f8d591ce95f01de5559e5d here. I just took a look and don't see anything that might cause that, but I could be overlooking something.

**Comment by jriram** [comment]
Guys, I found what the problem was:

I was using the `config.ru` file from https://langui.sh/2012/11/02/building-a-ca-r509-howto/ Changing to use the one in https://raw.github.com/r509/r509-ca-http/master/config.ru solves it.

Sorry for the inconvenience.

**Comment by reaperhulk** [comment]
Sounds like that howto needs to be updated. I'll take a look.

**Comment by reedloden** [comment]
@reaperhulk probably would be good just to remove the config.ru from your blog, as the gems themselves contain it already... or at least just link directly to github for those who just install the gems via rubygems :)
